### ISSUE TITLE
Pour tester alternc-certbot permettre l'utilisation du service de "staging" de letsencrypt

### ISSUE THREAD

**Issue by sebas891** [AlternC/alternc-acme#27]
Sinon, on se retrouve avec l'erreur...  too many certificates already issued for: issued for: koumbit.net: see https://letsencrypt.org/docs/rate-limits/",
`

Si on pouvait utiliser l'environnement staging de LE pour faire des testes. On évite ainsi de frapper les limites de requête sur les serveurs de LE et d'être barré pendant 1 semaine...

Il suffit d'ajouter l'option --staging sur les commande de certbot.

On peut également ajouter le faux certificat root ( Fake LE Root X1 ) à un navigateur de teste pour qu'il reconnaissent valide les certificats staging.

voir les détails pour la production https://letsencrypt.org/docs/rate-limits/
en gros une limite de 20 par semaine.

voici pour le staging : https://letsencrypt.org/docs/staging-environment/
en gros une limite de 30 000 par semaine...

**Comment by sebas891** [comment]
#20 est en parti relié...

**Comment by camlafit** [comment]
Hello

Cela est fait on test "localement" via le mode staging qui évite de tenter la génération de certificats invalides
