### ISSUE TITLE
Multipe ip : can't check localAlterncDomain

### ISSUE THREAD

**Issue by camlafit** [AlternC/alternc-acme#34]
In some case we can have multiple IP on server (failover, ....)

isLocalAlterncDomain method check only L_PUBLIC_IP value. Should more complete and check ip add values

**Comment by camlafit** [comment]
Ok another sub case.
During a migration process, previous server can act as proxy in this case L_PUBLIC_IP is not correct.

Should be an option or a list allowed ip

**Comment by kienanstewart** [comment]
PR #58 sounds like it will address this issue

**Comment by camlafit** [comment]
Hello

With new method to check local domain we can close this issue.

Please to reopen or comment again if required :)
