### ISSUE TITLE
Use a root ns in +trace query

### ISSUE THREAD

**Issue by camlafit** [AlternC/alternc-acme#35]
As said by @kent1D we can have some use case where dig +trace get an empty result.

More information can be found here :
https://docs.menandmice.com/pages/viewpage.action?pageId=6361009

We could force to root server in our query

**Comment by soul9** [comment]
Maybe check whether the +trace lookup fails, and if it does then use a root server.

**Comment by camlafit** [comment]
No more required as we have change local test
