### ISSUE TITLE
temps pour nouvelle release?

### ISSUE THREAD

**Issue by lelutin** [AlternC/alternc-acme#52]
Salut!

Ça fait déjà qq temps que la dernière version d'alternc-certbot, 0.0.15, a été taggée: c'était en juin 2018.

Il y a eu plusieurs changements et quelques bug fixes depuis qu'on aimerait bien pouvoir utiliser.

est-ce que l'état du code sur master est assez fonctionnel pour qu'on se permette de faire une release 0.0.16? est-ce qu'il y a des bugs qui ont été rapportés qu'on aimerait fixer avant?

**Comment by camlafit** [comment]
Bonjour

Oui je dois faire une repasse sur les PR et Demandes en attente et voir
pour faire une merge.
D'autant plus que alternc stretch est fonctionnelle et qu'en l'état la
0.0.15 n'est pas parfaite sur ce point.

**Comment by camlafit** [comment]
Salut

J'ai commencé à reporter le patch koumbit. Je sais qu'il fonctionne meme si je pense qu'on peut faire plus propre.
ça devrait nous donner une 0.0.16 sous peu

**Comment by lelutin** [comment]
super! merci pour le travail!

**Comment by camlafit** [comment]
Bon comme nightly et 0.0.18 sont sorties maintenant; on peut fermer :)
