### ISSUE TITLE
Certbot renewal outputs message using --quiet

### ISSUE THREAD

**Issue by Mazamazine** [AlternC/alternc-acme#62]
Running `/usr/lib/alternc/install.d/alternc-certbot apache2 --quiet --all` returns this output:
`Finished renewal for system certificates`

It shouldn't output anything with the `--quiet` option. 

This is due to the use of `vprintf()` in generate_certbot.php at line 88, instead of `vprint()` (which is defined at line 48 and checks for the global `$verbose` variable).

**Comment by Mazamazine** [comment]
PR https://github.com/AlternC/alternc-certbot/pull/63

**Comment by camlafit** [comment]
Hello

Could you update your PR. As project was renaming file is no more alternc-certbot but alternc-acme.

Thanks a lot
